weather_app_study/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#resource :weathers, only: [:index] do
#  get "/info", action: 'show'
#end

get '/weathers', to: 'weathers#index'
get '/weathers/info', to: 'weathers#info'

end

weather_app_study/app/models/weather.rb
class Weather < ApplicationRecord
end

weather_app_study/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

weather_app_study/app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
  require 'json'
  require 'time'
  require 'open-uri'
  require 'nokogiri'

  DARK_SKY_URI = 'https://api.darksky.net/forecast/080fa7f90e3e587b2de824aa0bcc0dd4/'
  
  #検索画面
  def index
    
  end
  

  #天気情報画面
  def info
    
    #経度と緯度を取得
    address = params[:address]
    @address = address
    geo_uri = URI.encode "https://www.geocoding.jp/api/?q=#{address}"
    
    xml = Nokogiri::XML(open(geo_uri).read)
    latitude = xml.xpath('/result/coordinate/lat').text.to_i
    longitude = xml.xpath('/result/coordinate/lng').text.to_i


    #お天気APIに経度と緯度を代入して、情報を取得
    uri = DARK_SKY_URI
    url = "#{uri}#{latitude},#{longitude}"
    @url = "#{uri}#{latitude},#{longitude}"
    
    response = open(url).read
    response_precip_hour = open("#{url}?extend=hourly").read

    weather = JSON.parse(response)
    precip_hour = JSON.parse(response_precip_hour)

    #今日の天気情報を取得
    def fahrenheit_to_celsius(temperature)
      ((temperature-32)/1.8).floor(2)
    end

    @today_weather = weather["currently"]["icon"]
    @temp_low = fahrenheit_to_celsius(weather["daily"]["data"][0]["apparentTemperatureMin"])
    @temp_high =fahrenheit_to_celsius(weather["daily"]["data"][0]["apparentTemperatureMax"])
    @precip = ((weather["daily"]["data"][0]["precipProbability"])*100).floor(2)

    #4時間ごとの天気
    hour_num = [4,8,12,16,20,24]
    res_hour = []
    
    hour_num.each do |num|
      res_hour << precip_hour["hourly"]["data"][num]["precipProbability"]
    end
     
    test = []

    res_hour.each.with_index(1) do |x, i|
      hour = i*4
      per = (x*100).floor(2)
      test << "[#{hour}時間後の降水確率:#{per}%]"
    end
    @res_4hour = test

   #前日/翌日の天気
   def weather_of_another_day(offset)
     yesterday_or_tomorrow = (Date.today + offset).to_s
     unixtime = Time.parse(yesterday_or_tomorrow).to_i
     response = open("#{@url},#{unixtime}").read
     weather = JSON.parse(response)
     weather["currently"]["icon"]
   end

   yesterday = -1
   tomorrow = 1
   yesterday.freeze
   tomorrow.freeze

   @yesterday_weather = weather_of_another_day(yesterday)
   @tomorrow_weather = weather_of_another_day(tomorrow)


   #1週間の天気
   week = []

   for num in 1..7 do
     unixtime_week = (Date.today+num).to_s
     unixtime_week = Time.parse(unixtime_week).to_i
     response_week = open("#{url},#{unixtime_week}").read
     weather_week = JSON.parse(response_week)
     week_weather = weather_week["currently"]["icon"]
     week << "[#{num}日後の天気:#{week_weather}]"
   end

   @week = week
  end

end

weather_app_study/app/helpers/weathers_helper.rb
module WeathersHelper
end

weather_app_study/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherAppStudy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

weather_app_study/app/views/weathers/index.html.erb
<h1>お天気エリア検索</h1>

<%= form_tag weathers_info_path, method: 'get' do %>
  <%= label_tag :address, 'エリアを入力してください' %><br>
  <%= text_field_tag :address %><br>
  <%= submit_tag '検索' %>
<% end %>

weather_app_study/app/views/weathers/info.html.erb
<h1><%= @address %>のお天気情報</h1>
<h2><%= "今日の天気:#{@today_weather}" %></h2>
<%= @weather_img %>

<% if @today_weather.include?("sun")%>
   <%= image_tag 'sunny.png' %>
<% elsif @today_weather.include?("clo") %>
   <%= image_tag 'cloudy.png' %>
<% elsif @today_weather.include?("rai") %>
   <%= image_tag 'rainy.png'%>
<% else %>
    <h2>no_img</h2>
<% end %>

<br>

<%= link_to '他エリアのお天気情報を見る', weathers_path %>

<h3><%= "今日の最高気温:#{@temp_high}度" %></h3>
<h3><%= "今日の最低気温:#{@temp_low}度" %></h3>

<h3><%= "今日の降水確率:#{@precip}%" %></h3>
<h4><%= @res_4hour.join(",") %><h4>

<h2><%= "明日の天気:#{@tomorrow_weather}"%><h2>
<h2><%= "前日の天気:#{@yesterday_weather}"%><h2>
<h4><%= @week.join(",") %></h4>

weather_app_study/app/views/weathers/show.html.erb
<p>show</p>