curd/config/routes.rb
Rails.application.routes.draw do
  resources :companies do
    resources :groups do
      resources :users do
        resources :name_cards
      end
    end
  end
  resources :companies do
    post :comment, on: :member
  end
end

curd/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

curd/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :company

  validates :name, presence: true
  validates :body, presence: true
end

curd/app/models/company.rb
class Company < ApplicationRecord
  has_many :groups
  has_many :comments

  validates :name, presence: true, length: {maximum: 100}
  validates :address, presence: true, length: {maximum: 100}
  validates :url, length: {maximum: 100}, format: URI.regexp(['http','https']), allow_blank: true
  validates :tel, :fax, format: {with: /\A[0-9]{2,4}-[0-9]{2,4}-[0-9]{4}\Z/}, allow_blank: true

end

curd/app/models/group.rb
class Group < ApplicationRecord
  belongs_to :company
  has_many :users

  validates :name, presence: true, length: {maximum: 100}
end

curd/app/models/name_card.rb
class NameCard < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, length: {maximum: 100}
  validates :address, length: {maximum: 100}, presence: true
  validates :url, length: {maximum: 100, allow: nil}, format: URI.regexp(['http', 'https']), allow_nil: true
  validates :tel, :fax, format: {with: /\A[0-9]{2,4}-[0-9]{2,4}-[0-9]{4}\Z/}
end

curd/app/models/post.rb
class Post < ApplicationRecord
  def search
    if search
      Post.where(['content LIKE ?', "%#{search}"])
    else
      Post.all
    end
end

curd/app/models/user.rb
class User < ApplicationRecord
  belongs_to :group
  has_many :name_cards

  validates :name, presence: true, length: { maximum: 100 }
  validates :tel, format: {with: /\A[0-9]{2,4}-[0-9]{2,4}-[0-9]{4}\Z/}
  validates :mail, length: { maximum: 100, minimun: 3 }, allow_blank: true, uniqueness: true, format: { with: /\A[A-Z0-9\.\_\-_+]+@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
end

curd/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # protect_from_forgery with: :execption
  
  before_action :set_company, :set_group

  def set_company
    id = params[:company_id] ? params[:company_id] : params[:id]
    @company = Company.find(id)
  end

  def set_group
    group_id = params[:group_id] ? params[:group_id] : params[:id]
    @group = @company.groups.find(group_id)
  end

  def set_user
    user_id = params[:user_id] ? params[:user_id] : params[:id]
    @user = @group.users.find(user_id)
  end

  def search
    @posts = Post.search(params[:search])
  end
end

curd/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
before_action :set_company, except: [:index, :new, :create]
skip_before_action :set_group

def index
  @companies = Company.all
end

def show
end

def new
  @company = Company.new
end

def edit
end

def create
  @company = Company.new(company_params)

  if @company.save
    redirect_to @company, notice: '会社を追加しました'
  else
    render action: 'new'
  end
end

def update
  if @company.update(company_params)
    redirect_to @company, notice: '更新しました'
  else
    render action: 'edit'
  end
end

def destroy
  @company.destroy
  redirect_to companies_url
end


def comment
  @company_comment = Company.find(params[:id])
  @comment = Comment.new(comment_params.merge(company_id: @company_comment.id))
  @comment.save!
    redirect_to action: :show, notice: '成功'
  rescue
    render action: :show, notice: '失敗'
end


private

def company_params
  params.require(:company).permit(:name, :address, :tel, :fax, :url)
end

def comment_params
  params.require(:comment).permit(:name, :body)
end

end

curd/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_company
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    @groups = @company.groups
  end

  def show
  end

  def new
    @group = @company.groups.new
  end

  def create
   @group = @company.groups.new(group_params)

   if @group.save
     redirect_to [@company, @group], notice: '部署を追加しました'
   else
     render action: 'new'
   end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to [@company, @group], notice: '更新しました'
    else
      render action: 'edit'
    end
  end

  def destroy
    @group.destroy
    redirect_to company_groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end

end

curd/app/controllers/name_cards_controller.rb
class NameCardsController < ApplicationController
  before_action :set_company, :set_group, :set_user
  before_action :set_name_card, only: [:show, :edit, :update, :destroy]

  def index
    @name_cards= @user.name_cards
  end

  def show
  end

  def new
    @name_card = @user.name_cards.new
  end

  def create
    @name_card = @user.name_cards.new(name_card_params)

    if @name_card.save
      redirect_to [@company, @group, @user, @name_card], notice: 'NameCard was succeessfully created'
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @name_card.update(name_card_params)
      redirect_to [@company, @group, @user, @name_card], notice: 'NameCard was successfully updated'
    else
      render action: 'edit'
    end
  end

  def destroy
    @name_card.destroy
    redirect_to company_group_user_name_cards_path
  end

  private


  def set_name_card
    @name_card = @user.name_cards.find(params[:id])
  end

  def name_card_params
    params.require(:name_card).permit(:name, :address, :fax, :tel, :url)
  end

end

curd/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def search
    @posts = Post.search(params[:search])
  end
end

curd/app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_company, :set_group
before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = @group.users
  end

  def show
  end

  def new
    @user = @group.users.new
  end

  def create
    @user = @group.users.new(user_params)

    if @user.save
      redirect_to [@company, @group, @user], notice: '部署を追加しました.'
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to [@company, @group, @user], notice: '追加しました'
    end
  end

  def destroy
    @user.destroy
    redirect_to company_group_users_path(@company, @group)
  end

  private

  def user_params
    params.require(:user).permit(:name, :mail, :tel)
  end

end

curd/app/helpers/application_helper.rb
module ApplicationHelper
end

curd/app/helpers/companies_helper.rb
module CompaniesHelper
end

curd/app/helpers/groups_helper.rb
module GroupsHelper
end

curd/app/helpers/name_cards_helper.rb
module NameCardsHelper
end

curd/app/helpers/users_helper.rb
module UsersHelper
end

curd/app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_exp;anation">
    <h2><%= pluralize(@company.errors.count, 'エラー') %>saved</h2>

    <ul>
    <% @company.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :会社名 %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :住所 %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :電話番号 %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :ファックス %><br>
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :Webサイト %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit "更新する"%>
  </div>
<% end %>

curd/app/views/companies/edit.html.erb
<h1>編集画面</h1>

<%= render 'form' %>

<%= link_to '会社詳細', @company, class:'btn btn-default' %>
<%= link_to '会社一覧へ戻る', companies_path, class:'btn btn-default' %>

curd/app/views/companies/index.html.erb
<h2>会社一覧</h2>


<table class="table table-hover">
  <thead>
    <tr>
      <th>会社名</th>
      <th>住所</th>
      <th>電話番号</th>
      <th>ファックス</th>
      <th>Webサイト</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
    <tr>
      <td><%= company.name %></td>
      <td><%= company.address %></td>
      <td><%= company.tel %></td>
      <td><%= company.fax %></td>
      <td><%= link_to "#{company.url}", "#{company.url}" %></td>
      <td><%= link_to '詳細', company, class:'btn btn-default' %>
          <%= link_to '編集', edit_company_path(company), class:'btn btn-default' %>
          <%= link_to '削除', company, method: :delete, data: {confirm: '削除しますか?'} , class:'btn btn-default'%>
          <%= link_to '部署一覧へ', company_groups_path(company), class:'btn btn-default' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to '会社を新規登録する', new_company_path, class:'btn btn-default' %>

curd/app/views/companies/new.html.erb
<h1>新規登録</h1>

<%= render 'form' %>

<%= link_to '会社一覧へ戻る', companies_path, class:'btn btn-default' %>

curd/app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>


<table class="table table-hover">
  <thead>
    <th>会社名</th>
    <th>住所</th>
    <th>電話番号</th>
    <th>ファックス</th>
    <th>Webサイト</th>
  </thead>

  <tbody>
    <tr>
    <td><%= @company.name %></td>
    <td><%= @company.address %></td>
    <td><%= @company.tel %></td>
    <td><%= @company.fax %></td>
    <td><%= @company.url %></td>
    </tr>
  </tbody>
</table>

<%= form_for Comment.new ,url: comment_company_path(@company) do |f| %>
<%= f.text_area :body %><br>
<%= f.submit '投稿' %>
<% end %>

<br>


<%= link_to '編集', edit_company_path(@company), class:'btn btn-default' %>
<%= link_to '部署一覧へ', company_groups_path(@company), class:'btn btn-default' %>
<%= link_to '会社一覧へもどる', companies_path, class:'btn btn-default' %>

curd/app/views/groups/_form.html.erb
<%= form_for([@company, @group]) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, 'error') %> saved </h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :部署名 %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "更新する"%>
  </div>
<% end %>

curd/app/views/groups/edit.html.erb
<h1>編集画面</h1>

<%= render 'form' %>

<%= link_to '詳細', company_group_path(@company, @group), class:'btn btn-default' %>
<%= link_to '部署一覧へもどる', company_groups_path(@company, @group), class:'btn btn-default' %>

curd/app/views/groups/index.html.erb
<h2>部署一覧(<%= @company.name %>)</h2>

<table class="table table-hover" >
  <thead>
    <tr>
      <th>部署名</th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= link_to '詳細', company_group_path(@company, group), class:'btn btn-default' %>
            <%= link_to '編集', edit_company_group_path(@company, group), class:'btn btn-default' %>
            <%= link_to '削除', company_group_path(@company, group), method: :delete, data: { confirm: '削除してもいいですか?' }, class:'btn btn-default' %>
             <%= link_to '社員一覧へ', company_group_users_path(@company, group), class:'btn btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '部署を追加する', new_company_group_path(@company), class:'btn btn-default' %>
<%= link_to '会社一覧へ戻る', companies_path, class:'btn btn-default' %>

curd/app/views/groups/new.html.erb
<h1>新規登録画面</h1>

<%= render 'form' %>

<%= link_to '部署一覧へ戻る', company_groups_path(@company), class:'btn btn-default' %>

curd/app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>部署名:</strong>
  <%= @group.name %>
</p>

<%= link_to '編集', edit_company_group_path(@company, @group), class:'btn btn-default' %>
<%= link_to '社員一覧', company_group_users_path(@company, @group), class:'btn btn-default' %>
<%= link_to '部署一覧へ戻る', company_groups_path(@company), class:'btn btn-default' %>

curd/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Curd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div id="wrap">
    <div class="container">

      <div>
        <ul class="nav nav-tabs">
          <strong><li class="active">名刺管理アプリ</li></strong>
          <li role="presentation"><a href="#">Link1</a></li>
          <li role="presentation"><a href="#">Link2</a></li>
          <li role="presentation"><a href="#">Link3</a></li>
        </ul>
      </div>

       
      <%= yield %>

    </div>
   </div>

      <footer class="footer">
        <div class="container">
          <p class="text-muted">2018 名刺管理アプリ</p>
        </div>
      </footer>

  </body>
</html>

curd/app/views/name_cards/_form.html.erb
<%= form_for([@company, @group, @user, @name_card]) do |f| %>
  <% if @name_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@name_card.errors.count, "error") %> prohibited this name_card from being saved: </h2>

      <ul>
      <% @name_card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :tel %>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :fax %>
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>






<% end %>

curd/app/views/name_cards/edit.html.erb
<h1>Editing name_card</h1>

<%= render 'form' %>

<%= link_to 'Show', company_group_user_name_card_path(@company, @group, @user, @name_card) %> |
<%= link_to 'Back', company_group_user_name_cards_path %>

curd/app/views/name_cards/index.html.erb
<h1>名刺一覧(<%= @group.name %>)</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>氏名</th>
      <th>住所</th>
      <th>電話番号</th>
      <th>ファックス</th>
      <th>Webサイト</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
     <% @name_cards.each do |name_card| %>
       <tr>
         <td><%= name_card.name %></td>
         <td><%= name_card.address %></td>
         <td><%= name_card.tel %></td>
         <td><%= name_card.fax %></td>
         <td><%= name_card.url %></td>
         <td>
           <%= link_to '詳細', company_group_user_name_card_path(@company, @group, @user, name_card) %><br/>
           <%= link_to '編集', edit_company_group_user_name_card_path(@company, @group, @user, name_card) %><br/>
           <%= link_to '削除', company_group_user_name_card_path(@company, @group, @user, name_card), method: :delete, data: { confirm: '削除しますか?' } %>
       </td>
       </tr>
     <% end %>
  </tbody>
</table>

<br>

<%= link_to '名刺を追加する', new_company_group_user_name_card_path %>
<%= link_to '社員一覧へ戻る', company_group_users_path %>

curd/app/views/name_cards/new.html.erb
<h1>New name_card</h1>

<%= render 'form' %>

<%= link_to 'Back', company_group_user_name_cards_path %>

curd/app/views/name_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>:</strong>
  <%= @name_card.name %>
</p>
<p>
  <strong>:</strong>
  <%= @name_card.address %>
</p>
<p>
  <strong>:</strong>
  <%= @name_card.tel %>
</p>
<p>
  <strong>:</strong>
  <%= @name_card.fax %>
</p>
<p>
  <strong>:</strong>
  <%= @name_card.url %>
</p>

<%= link_to 'Edit', edit_company_group_user_name_card_path(@company, @group, @user, @name_card) %> |
<%= link_to 'Back', company_group_user_name_cards_path %>

curd/app/views/users/_form.html.erb
<%= form_for([@company, @group, @user]) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, 'エラー') %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :氏名 %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :メールアドレス %><br>
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :電話番号 %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="actions">
    <%= f.submit "更新する" %>
  </div>
<% end %>

curd/app/views/users/edit.html.erb
<h1>編集する</h1>

<%= render 'form' %>

<%= link_to '詳細', company_group_user_path(@company, @group, @user), class:'btn btn-default' %>
<%= link_to '社員一覧へもどる', company_group_users_path(@company, @group), class:'btn btn-default' %>

curd/app/views/users/index.html.erb
<h2>社員一覧（<%= @company.name %>:<%= @group.name %>）</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>電話番号</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
         <td><%= user.name %></td>
         <td><%= user.mail %></td>
         <td><%= user.tel %></td>
         <td>
           <%= link_to '詳細', company_group_user_path(@company, @group, user), class:'btn btn-default'  %>
           <%= link_to '編集', edit_company_group_user_path(@company, @group, user), class:'btn btn-default' %>
           <%= link_to '削除', company_group_user_path(@company, @group, user), method: :delete, data: { confirm: '削除しますか？' }, class:'btn btn-default' %><br />
         </td>
       </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '社員を追加する', new_company_group_user_path(@company, @group), class:'btn btn-default' %>
<%= link_to '部署一覧へ戻る',company_groups_path(@company), class:'btn btn-default' %>

curd/app/views/users/new.html.erb
<h1>新規登録画面</h1>

<%= render 'form' %>

<%= link_to '社員一覧へ戻る', company_group_users_path(@company, @group) %>

curd/app/views/users/show.html.erb
<p id="notice" ><%= notice %></p>

<p>
  <strong>氏名:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>メールアドレス:</strong>
  <%= @user.mail %>
</p>
<p>
  <strong>電話番号:</strong>
  <%= @user.tel %>
</p>
<%= link_to '編集', edit_company_group_user_path(@company, @group, @user), class:'btn btn-default' %>
<%= link_to '名刺一覧', company_group_user_name_cards_path(@company, @group, @user), class:'btn btn-default' %>
<%= link_to '社員一覧へ戻る', company_group_users_path(@company, @group), class:'btn btn-default' %>